title: John Wamalwa
email: 254wamalwa@gmail.com
description: Welcome to John Wamalwa's digital portfolio. A hub showcasing expertise in cybersecurity, ICT and data analytics. 
  Explore innovative projects, insightful write-ups and technical challenges that highlight my problem-solving skills 
  and commitment to data-driven security solutions. Dive into research, development and strategies that secure and enhance 
  the digital landscape. Let's connect, innovate and shape the future of technology together!
linkedin_username: John Wamalwa
github_username: wamalwaj
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone:  https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "John Wamalwa"
  avatar : "/assets/images/Passport.jpg"
  bio    : "Mathematics & Computer Science graduate specializing in Security Engineering, Data Analytics and ICT solutions. Passionate about leveraging technology to secure systems, optimize data insights and drive innovation in the digital space."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://wamalwaj.github.io"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin_username-square"
      url: "https://www.linkedin.com/in/john-w-746a80211"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wamalwaj"
    - #label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/john-w-746a80211"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wamalwaj"
    - #label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/add"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
